# The python Programming Language: Functions

In [32]:
x=1
y=2
x+y

3

In [33]:
x

1

In [34]:
def add_numbers(x,y,z):
    return x+y+z


add_numbers(1,2,3)


6

In [35]:
def add_numbers(x,y,z=None):
    if (z==None) :
        return x+y
    else:
        return x+y+z

add_numbers(1,2)


3

# The Python Programming Language: Types and Sequences

In [36]:
type('This is a string')

str

In [37]:
type(None)

NoneType

In [38]:
type(1)

int

In [39]:
type(1.0)

float

In [40]:
type(add_numbers)

function

Tuples are an immutable data structure (cannot be altered).

In [41]:
x=(1,'a',2,'b')
type(x)

tuple

Lists are a mutable data structure.

In [42]:
x = [1, 'a', 2, 'b']
type(x)

list

In [43]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [44]:
for item in x:
    print(item)

1
a
2
b
3.3


In [45]:
# Or using the indexing operator:
i = 0
while (i != len(x)):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


Use `+` to concatenate lists.

In [46]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

Use `*` to repeat lists.

In [47]:
[1] * 3

[1, 1, 1]

Use the `in` operator to check if something is inside a list.

In [48]:
1 in [1, 2, 3]

True

In [49]:
# Now let's look at strings. Use bracket notation to slice a string.


x='This is a string'


print(x[0]) #first character 
print(x[0:1]) ##first character, but we have explicitly set the end character
print(x[0:2])   #first two characters



T
T
Th


In [50]:
# this will return the last character 
print(x[-1])

# this will start from the fourth element from the end and stop before the second element from the end
x[-4:-2]
# this is a slace starting from the beginning and stops before the 4 th element of the string 4
x[:4]

# And this is a slice start from the 4th element and gpoing all the way to the end of the string
x[3:]

g


's is a string'

In [51]:
fName= 'Christopher'
lName="Brooks"
print(fName+' '+lName)
print(fName*3)
print('Chris' in fName)


Christopher Brooks
ChristopherChristopherChristopher
True


`split` returns a list of all the words in a string, or a list split on a specific character.

In [52]:
firstName='Christopher Arthur Hansen Brooks'.split(' ')[0]
lastName='Christopher Arthur Hansen Brooks'.split(' ')[-1]

In [53]:
print(firstName)
print(lastName)

Christopher
Brooks


In [54]:
# Make sure you convert objects to strings before concatenating.
'chris'+str(2)

'chris2'

In [55]:
x={'Christopher brooks':'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher brooks']


'brooksch@umich.edu'

In [56]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

Iterate over all of the keys:

In [57]:
for i in x:
    print(x[i])

brooksch@umich.edu
billg@microsoft.com
None


Iterate over all of the values:

In [58]:
for value in x.values():
    print(value)

brooksch@umich.edu
billg@microsoft.com
None


Iterate over all of the items in the list:

In [59]:
for name,email in x.items():
    print(name,"------ ",email)

Christopher brooks ------  brooksch@umich.edu
Bill Gates ------  billg@microsoft.com
Kevyn Collins-Thompson ------  None


In [60]:
# Unpaking 
# You can unpack a sequence in different  variables :
x=('Christopher','Brooks',"Christopher.brooks@gmail.com")
fname,lname,email=x

In [61]:
fname
lname
email

'Christopher.brooks@gmail.com'

In [62]:
# Make sure the number of values you are unpacking matches the number of 
# variables being assigned.
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

# The Python Programming Language: More on Strings

In [63]:
print('Chris' +2)

TypeError: can only concatenate str (not "int") to str

In [67]:
print('Chris' +str(2))

Chris2


In [68]:
sales_record={
"price":3.24,
    'num_items':44,
    'person':'Chris'}


sales_statement='{} bought {} item(s) at a price of {} each for a total of {} dh'

print(sales_statement.format(sales_record['person'],
                            sales_record['num_items'],
                             sales_record['price'],
                             sales_record['price']*sales_record['num_items']
                            ))

Chris bought 44 item(s) at a price of 3.24 each for a total of 142.56 dh


# The Python Programming Language: Date and time

In [69]:
import datetime as dt
import time as tm

In [70]:
# return the number of seconds since the EPOCH : 1er janvier 1970

tm.time()

1719593933.919174

In [ ]:

dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2024, 6, 12, 12, 36, 21, 26393)

In [ ]:
# that's a tuple
dtnow.year,dtnow.month,dtnow.day,dtnow.hour,dtnow.minute,dtnow.second

(2024, 6, 12, 12, 36, 21)

In [ ]:
delta = dt.timedelta(days=100)
delta

datetime.timedelta(days=100)

In [ ]:
today= dt.date.today()

In [ ]:
today-delta

datetime.date(2024, 3, 4)

In [ ]:
today > (today-delta)

True

# The Python Programming Language: Objects and map()

In [ ]:
class Person:
    departement="School of code"
    def set_name(self,new_name):
        self.name=new_name

    def set_location(self,new_location):
        self.location=new_location

In [ ]:
person=Person()
person.set_location("My home")
person.set_name("abderahim elouady")

In [ ]:
print("i live in {} ,my name is {} and i work in {}1.".format(person.location,person.name,person.departement))

i live in My home ,my name is abderahim elouady and i work in School of code1.


Here's an example of mapping the `min` function between two lists.

In [ ]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]

cheapest=map(min,store1,store2)
cheapest
# leazy evaluation

map

In [ ]:
for i in cheapest:
    print(i)

9.0
11.0
12.34
2.01


 when we go to print out the map, we see that we get an odd reference value instead of a list of items that we're expecting. This is called lazy evaluation. In Python, the map function returns to you a map object. It doesn't actually try and run the function min on two items, until you look inside for a value. This is an interesting design pattern of the language, and it's commonly used when dealing with big data.

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']


# my solution
# def split_title_and_name(person):
#     return person.split(' ')[0] + person.split(' ')[2]
# # its better to put -1 in the split cz in some times the nume is composed of more than two
# return person.split(' ')[0] + person.split(' ')[-1]

# there solution
def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

list(map(split_title_and_name,people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

# The Python Programming Language: Lambda and List Comprehensions

In [ ]:
myfunction=lambda a,b:a+b
myfunction(1,2)

3

In [ ]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

# Option 1
for person in people:
    print(split_title_and_name(person) == (lambda p: p.split()[0] + ' ' + p.split()[-1])(person))

# Option 2
print(list(map(split_title_and_name, people)) == list(map(lambda p: p.split()[0] + ' ' + p.split()[-1], people)))


True
True
True
True
True


Option 1:

The for loop iterates over each person in the people list.
The split_title_and_name(person) function call is compared to the lambda function lambda p: p.split()[0] + ' ' + p.split()[-1](person).
The lambda function takes the same person input and returns the same output as split_title_and_name.
The corrected comparison ensures each iteration prints True if the function and lambda produce the same result.

Option 2:

The map function applies split_title_and_name to each item in the people list.
Similarly, map applies the lambda function to each item in the people list.
The comparison checks if both lists produced by map are equal.

In [ ]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [ ]:
my_list=[number for number in range(0,1000) if number%2==0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [ ]:
# List comprehension
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10)  for j in range(10)]

True

# NUMPY

Numpy is the fundamental package for numeric computing with Python. It provides powerful ways to create, store, and/or manipulate data, which makes it able to seamlessly and speedily integrate with a wide variety of databases. This is also the foundation that Pandas is built on, which is a high-performance data-centric package that we will learn later in the course.

In this lecture, we will talk about creating array with certain data types, manipulating array, selecting elements from arrays, and loading dataset into array. Such functions are useful for manipulating data and understanding the functionalities of other common Python data packages.

In [3]:

import numpy as np
import math 


# Array Creation

In [ ]:
# Arrays are displayed as a list or list of lists and can be created through list as well. When creating an
# array, we pass in a list as an argument in numpy array


a= np.array([1,2,32,3])


print(a)
# We can print the number of dimensions of a list using the ndim attribute
print("dimension",a.ndim)

[ 1  2 32  3]
dimension 1


In [ ]:
# if we pass a lisrt of list to the array it creates aa multi-dimension array
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(b.ndim)

# return a tuple (length of the first array,the length of the dimensions)
print(b.shape)

2
(2, 3)


In [ ]:
# We can also check the type of items in the array
a.dtype

dtype('int32')

In [ ]:
# Besides integers, floats are also accepted in numpy arrays
c = np.array([2.2, 5, 1.1])
c.dtype.name


'float64'

In [ ]:
# Let's look at the data in our array
c
# Note that numpy automatically converts integers, like 5, up to floats, since there is no loss of prescision.
# Numpy will try and give you the best data type format possible to keep your data types homogeneous, which
# means all the same, in the array

array([2.2, 5. , 1.1])

In [ ]:
# Sometimes we know the shape of an array that we want to create, but not what we want to be in it. numpy
# offers several functions to create arrays with initial placeholders, such as zero's or one's.
# Lets create two arrays, both the same shape but with different filler values
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# We can also generate an array with random numbers
np.random.rand(2,3)

array([[0.28343261, 0.05264166, 0.73263671],
       [0.51071836, 0.15110708, 0.29686455]])

In [ ]:
# We can also create a sequence of numbers in an array with the arrange() function. The fist argument is the
# starting bound and the second argument is the ending bound, and the third argument is the difference between
# each consecutive numbers

# Let's create an array of every even number from ten (inclusive) to fifty (exclusive)
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [ ]:
# if we want to generate a sequence of floats, we can use the linspace() function. In this function the third
# argument isn't the difference between two numbers, but the total number of items you want to generate
np.linspace( 0, 2, 15 ) # 15 numbers from 0 (inclusive) to 2 (inclusive)

# Array Operations

In [ ]:
# We can do many things on arrays, such as mathematical manipulation (addition, subtraction, square,
# exponents) as well as use boolean arrays, which are binary values. We can also do matrix manipulation such
# as product, transpose, inverse, and so forth.

In [73]:
# ARTTHMITICS
a=np.array([10,20,30,40])
b=np.array([1,2,56,4])

# a minus b
c=a-b
print(c)

# a plus b 
d=a+b
print(d)

# a times b 
e=a*b
print(e)


[  9  18 -26  36]
[11 22 86 44]
[  10   40 1680  160]


In [6]:
# With arithmetic manipulation, we can convert current data to the way we want it to be. Here's a real-world
# problem I face - I moved down to the United States about 6 years ago from Canada. In Canada we use celcius
# for temperatures, and my wife still hasn't converted to the US system which uses farenheit. With numpy I 
# could easily convert a number of farenheit values, say the weather forecase, to ceclius
ferenheit= np.array([0,-10,-5,-15,0])

# the formula for the conversion is ((°F-32)*5/9)=°C
celcius=((ferenheit-32)*5/9)
celcius
# sso i deed the same for the kelvin and the celcius :
kelvin= celcius+273,15
print(kelvin)

(array([255.22222222, 249.66666667, 252.44444444, 246.88888889,
       255.22222222]), 15)


In [7]:
# Another useful and important manipulation is the boolean array. We can apply an operator on an array, and a
# boolean array will be returned for any element in the original, with True being emitted if it meets the condition and False oetherwise.
# For instance, if we want to get a boolean array to check celcius degrees that are greater than -20 degrees
celcius > -20

array([ True, False, False, False,  True])

In [8]:
# Here's another example, we could use the modulus operator to check numbers in an array to see if they are even. Recall that modulus does division but throws away everything but the remainder (decimal) portion)
celcius%2 == 0

array([False, False, False, False, False])

In [21]:
# Besides elementwise manipulation, it is important to know that numpy supports matrix manipulation. Let's
# look at matrix product. if we want to do elementwise product, we use the "*" sign

A= np.array([[1,2],[5,6]])
B= np.array([[10,20],[50,60]])

# elementwise product:  performed element by element.
print("elementwise product : ",A*B)

# if we want to do matrix product, we use the "@" sign or use the dot function
print("matrix product : ",A@B)

elementwise product :  [[ 10  40]
 [250 360]]
matrix product :  [[110 140]
 [350 460]]


In [22]:
# You don't have to worry about complex matrix operations for this course, but it's important to know that
# numpy is the underpinning of scientific computing libraries in python, and that it is capable of doing both
# element-wise operations (the asterix) as well as matrix-level operations (the @ sign). There's more on this
# in a subsequent course.

In [23]:
# A few more linear algebra concepts are worth layering in here. You might recall that the product of two
# matrices is only plausible when the inner dimensions of the two matrices are the same. The dimensions refer
# to the number of elements both horizontally and vertically in the rendered matricies you've seen here. We
# can use numpy to quickly see the shape of a matrix:
A.shape

(2, 2)

In [28]:
# When manipulating arrays of different types, the type of the resulting array will correspond to 
# the more general of the two types. This is called upcasting.
array_one= np.array([[1,2,3],[4,5,6]])
array_two= np.array([[1.0,2.5,3.6],[4.3,5.1,6.2]])

print(array_one.dtype)
print(array_two.dtype)


int32
float64


In [ ]:
# Integers (int) are whole numbers only, and Floating point numbers (float) can have a whole number portion
# and a decimal portion. The 64 in this example refers to the number of bits that the operating system is
# reserving to represent the number, which determines the size (or precision) of the numbers that can be
# represented.

In [31]:
array_three=array_one+array_two
print(array_three)
# Notice how the items in the resulting array have been upcast into floating point numbers

[[ 2.   4.5  6.6]
 [ 8.3 10.1 12.2]]


In [32]:
# Numpy arrays have many interesting aggregation functions on them, such as  sum(), max(), min(), and mean()
print(array_three.min())
print(array_three.max())
print(array_three.mean())



2.0
12.2
7.283333333333334


In [34]:
# For two dimensional arrays, we can do the same thing for each row or column
# let's create an array with 15 elements, ranging from 1 to 15, 
# with a dimension of 3X5


three_five=np.arange(1,16,1).reshape(3,5)
print(three_five)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
# Now, we often think about two dimensional arrays being made up of rows and columns, but you can also think
# of these arrays as just a giant ordered list of numbers, and the *shape* of the array, the number of rows
# and columns, is just an abstraction that we have for a particular purpose. Actually, this is exactly how
# basic images are stored in computer environments.

# Let's take a look at an example and see how numpy comes into play.